# config.yaml

# 各空间测绘平台 API Key 配置（留空表示不使用该平台）
api_keys:
  fofa: ""
  quake: ""
  hunter: ""

# 查询参数设置
query:
  min_ips_per_cidr: 10          # 一个C段最少有几个IP才会被二次扫描
  min_urls_per_ip_for_flag: 10  # 同一个IP关联URL超过这个数量，标记为"需要手动扫描"
  interval_seconds: 3          # 每次查询后的间隔时间（秒），防止过于高频扫描导致查询失败

# 输入目标配置
input:
  target_file: "targets.csv"   # 默认读取目标文件路径，可为targets.txt或targets.csv

# 结果输出目录（可选，默认创建在 ./results/yyyyMMdd_xxxxxx）
output:
  base_dir: "./results"